spring:

#thymeleaf 配置
  thymeleaf:
    #内容类型
    #后缀
    suffix: .html
    #templates存放地址  前缀
    prefix: classpath:/templates/
    #编码格式
    encoding: UTF-8
    #缓存 在开发环境关闭防止页面不刷新   在生产环境开启提高性能
    cache: false
    #查找本地模板
    check-template-location: true
    mode: HTML5
    servlet:
      content-type: text/html

  mvc:
    view:
      suffix: .html
      prefix: /templates/

    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  #数据源配置
  datasource:
    url: jdbc:mysql://118.31.122.109:3399/ctg_sysmgr?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=UTC&useAffectedRows=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lG@lieWa2fWq

  #mail 配置
  mail:
    host: smtp.163.com
    port: 25
    username: z40403740@163.com
    password: zsj123456.z
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
      mail:
        smtp:
          ssl:
            enable: true

  #redis
#  redis:
#    host: 139.199.95.213
#    port: 6379
#    pool:
#      max-idle: 20
#      min-idle: 1
#      max-active: 20
#      max-wait: 60000
#    database: 0


#mybatis配置
mybatis:
  #mapper存放位置
  mapper-locations: classpath*:/mapping/*.xml
  #指定entity位置
#  type-aliases-package: com.zsj.springbootframework.entity
  configuration:
    #打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启懒加载
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  type-handlers-package: com.ideal.upms.service.dao.mapper.handler
